import { Menu } from '../_models';

export const bwsMenus: Menu[] = [
  {
    level: 1,
    title: 'Brokers',
    icon: 'user',
    path: ['/brokers'],
    open: false,
    selected: false,
    disabled: false,
    children: null,
  },
  {
    level: 1,
    title: 'Sales Summary',
    icon: 'stock',
    path: ['/summary'],
    open: false,
    selected: false,
    disabled: false,
    children: null,
  },
  {
    level: 1,
    title: 'Commission',
    icon: 'area-chart',
    path: ['/calculation/COMMN'],
    open: false,
    selected: false,
    disabled: false,
    children: null,
  },
  {
    level: 1,
    title: 'Bonus',
    icon: 'area-chart',
    path: ['/calculation/BONUS'],
    open: false,
    selected: false,
    disabled: false,
    children: null,
  },
  {
    level: 1,
    title: 'Payments',
    icon: 'dollar',
    path: ['/payment'],
    open: false,
    selected: false,
    disabled: false,
    children: null,
  },
];
